version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_PROWLARR_IP
      APP_PORT: $APP_PROWLARR_PORT
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/prowlarr:0.4.4-nightly@sha256:053efaf2ede2a8e85a960f6db0d6a54e2ca29b13910dc3575eb5a86c686ed302
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
    networks:
      default:
        ipv4_address: $APP_PROWLARR_IP

  mac:
    image: getumbrel/media-app-configurator:v1.0.0@sha256:e3d8b18e0186f76dd3f3d4acacc9101b4abbf302d8f2afbb47cdd3879b1a1008
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    environment:
      DOWNLOAD_CLIENT_API_URL: "http://${APP_PROWLARR_IP}:${APP_PROWLARR_PORT}/api/v1/downloadclient"
      TRANSMISSION_HOST: "transmission_server_1"
      TRANSMISSION_PORT: 9091
