version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_KRYSTAL_BULL_IP
      APP_PORT: 3001
  
  web:
    image: bitcoinscala/oracle-server-ui:1.9.5@sha256:30f289d5d885f3eecb6744abc2ddc3d24e44816771baacfbb9646228f71615f5
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/bitcoin-s
      - ${APP_DATA_DIR}/data/log:/log
    environment:
      LOG_PATH: "/log/"
      BITCOIN_S_HOME: "/bitcoin-s/"
      ORACLE_SERVER_API_URL: "http://${APP_KRYSTAL_BULL_SERVER_IP}:9998/"
      TOR_PROXY: socks5://${TOR_PROXY_IP}:${TOR_PROXY_PORT}
      DEFAULT_UI_PASSWORD: "none"
      BITCOIN_S_ORACLE_RPC_PASSWORD: $APP_PASSWORD
    networks:
      default:
        ipv4_address: $APP_KRYSTAL_BULL_IP
    depends_on: 
      - oracleserver
  
  oracleserver:
    image: bitcoinscala/bitcoin-s-oracle-server:1.9.5@sha256:a08b8c429560e1dea99fb6f6d5492e88e89a97538f546720868b284bc93f56f4
    entrypoint: ["/opt/docker/bin/bitcoin-s-oracle-server", "--datadir", "/bitcoin-s", "--conf", "/opt/docker/docker-application.conf"]   
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/bitcoin-s
    environment:
      BITCOIN_S_KEYMANAGER_ENTROPY: $APP_SEED
      BITCOIN_S_ORACLE_RPC_PASSWORD: $APP_PASSWORD
      DISABLE_JLINK: "1"
    networks:
      default:
        ipv4_address: $APP_KRYSTAL_BULL_SERVER_IP
