version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_THUNDERHUB_IP
      APP_PORT: $APP_THUNDERHUB_PORT
      
  web:
    image: iraszl/lnpclient:v0.1.3
    restart: on-failure
    stop_grace_period: 1m
    environment:
      # LND connection details
      LN_SERVER_URL: "https://$APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_REST_PORT"
      MACAROON_PATH: "/lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK"
      CONFIG_PATH: "/lnd/lnd.conf"

      # App Config
      LN_IMPLEMENTATION: "LND"

    networks:
      default:
        ipv4_address: $APP_THUNDERHUB_IP
