version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_BTC_RPC_EXPLORER_IP
      APP_PORT: $APP_BTC_RPC_EXPLORER_PORT
      
  web:
    image: iraszl/lnpclient:v0.1.5
    restart: on-failure
    stop_grace_period: 1m
    environment:
      # LND connection details
      LN_SERVER_URL: "https://$APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_REST_PORT"
      MACAROON_PATH: "/home/ubuntu/umbrel/app-data/lightning/data/lnd/data/chain/bitcoin/mainnet/admin.macaroon"
      CONFIG_PATH: "/lnd/lnd.conf"

      # App Config
      LN_IMPLEMENTATION: "LND"

    networks:
      default:
        ipv4_address: $APP_BTC_RPC_EXPLORER_IP
