version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_LIDARR_IP
      APP_PORT: $APP_LIDARR_PORT
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/lidarr:1.0.2@sha256:890b8b35aa1e6509f61ee3efab0691a4360ca257489cb535dbc1c49fa3093a56
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
    networks:
      default:
        ipv4_address: $APP_LIDARR_IP

  mac:
    image: getumbrel/media-app-configurator:v1.0.0@sha256:e3d8b18e0186f76dd3f3d4acacc9101b4abbf302d8f2afbb47cdd3879b1a1008
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    environment:
      DOWNLOAD_CLIENT_API_URL: "http://${APP_LIDARR_IP}:${APP_LIDARR_PORT}/api/v1/downloadclient"
      ROOT_FOLDER_API_URL: "http://${APP_LIDARR_IP}:${APP_LIDARR_PORT}/api/v1/rootfolder"
      TRANSMISSION_HOST: "transmission_server_1"
      TRANSMISSION_PORT: 9091
      ROOT_FOLDER: "/downloads/music"
