version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_TRANSMISSION_IP
      APP_PORT: 9091

  server:
    image: linuxserver/transmission:version-3.00-r5@sha256:f0b885f211dd6fde7b64f0d6b9e5931929cfc2331fb83d6f3171e412f22b3f87
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: on-failure
    networks:
      default:
        ipv4_address: $APP_TRANSMISSION_IP
