version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_LIGHTNING_TERMINAL_IP
      APP_PORT: $APP_LIGHTNING_TERMINAL_PORT

  web:
    image: lightninglabs/lightning-terminal:v0.8.0-alpha@sha256:2533a567181d26c6faa6d8c8226bb3844aa78eb7de74cdcb1530e83bd56f3ca6
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
    environment:
      HOME: "/data"
      APP_PASSWORD: "$APP_PASSWORD"
    command:
        - --uipassword_env=APP_PASSWORD
        - --insecure-httplisten=0.0.0.0:$APP_LIGHTNING_TERMINAL_PORT
        - --network="$APP_BITCOIN_NETWORK"
        - --lnd-mode="remote"
        - --remote.lnd.rpcserver=$APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_GRPC_PORT
        - --remote.lnd.macaroonpath="/lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK/admin.macaroon"
        - --remote.lnd.tlscertpath="/lnd/tls.cert"
    networks:
      default:
        ipv4_address: $APP_LIGHTNING_TERMINAL_IP
